### ISSUE TITLE
DecompressionBombWarning

### ISSUE THREAD

**Issue by einervonvielen** [einervonvielen/family-scripts#1]
```
python3 collect.py -v -r -i ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/
Directory for faces not given as param. Take default dir = faces
Read '0' image(s) from DB in directory ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/
Skipping file because it is no image ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/.faces_of_dir.db
Read '1' image(s) from files in directory ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/
Use all CPUs for dir ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/
Load face encodings from IMAGE... ../Schritt_2_in_Entwicklung_bei_Darktable/pano_temp/20080817-Pano_Goor-Vilm_54464Pixel.jpg
/usr/lib/python3/dist-packages/PIL/Image.py:2274: DecompressionBombWarning: Image size (260316216 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning)
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/media/nuci/intenso/familie/Bilder/faces/face_util.py", line 121, in collect_faces_image
    face_encodings = face_recognition.face_encodings(image)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 209, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 153, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
MemoryError: std::bad_alloc
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "collect.py", line 114, in <module>
    face_util.collect_faces_of_dir(dir, is_verbose, True, dir_faces_unknown)
  File "/media/nuci/intenso/familie/Bilder/faces/face_util.py", line 73, in collect_faces_of_dir
    for details, result in zip(images_to_read, executor.map(collect_faces_image, images_to_read)):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
MemoryError: std::bad_alloc
```

**Comment by einervonvielen** [comment]
Fixed by https://github.com/einervonvielen/family-scripts/commit/d0e043747c6fe26ee4d04a963790ce927c44b496
